services:
  db:
    image: mysql:8.0
    container_name: flash_sale_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flash_sale
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

